OLED_ENABLE = no
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
CAPS_WORD_ENABLE = yes    # Enable caps word function
MOUSEKEY_ENABLE = yes # enable mouse keys support
LEADER_ENABLE = yes # enable Leader Key
TAP_DANCE_ENABLE = yes # enable Tap Dance
AUTO_SHIFT_ENABLE = yes # enable Auto Shift (Used only for num pad keys)
